// <auto-generated />
using Eroski.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eroski.Migrations
{
    [DbContext(typeof(SessionesContext))]
    [Migration("20211220093323_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Eroski.Models.Session", b =>
                {
                    b.Property<string>("nSeccion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Ticket")
                        .HasColumnType("int");

                    b.HasKey("nSeccion");

                    b.ToTable("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
